### ISSUE TITLE
EPIC: As PM of the project Solda I need to set up the infrastructure for the reference implementation of the DevOps toolchain.

### ISSUE THREAD

**Issue by LucaMiotto** [idm-suedtirol/reuse#8]
- [x] Support Alberto Pianon, Array to set up a reference implementation of the DevOps toolchain (WP3)
- [x] Support transition from reference implementation on NOI infrastructure to Huawei production environment
- [x] Create documentation of step-by-step installation of reference implementation

**Comment by Piiit** [comment]
@bertolla How should I test this? Could you provide some information, please...

**Comment by bertolla** [comment]
https://gitlab.com/noi-techpark/ohos/fossology-wrapper/-/merge_requests/2

**Comment by Piiit** [comment]
> Support transition from reference implementation on NOI infrastructure to Huawei production environment
@LucaMiotto Does this mean, that we just have to answer questions, when necessary? Can we close this checkbox?

**Comment by Piiit** [comment]
> https://gitlab.com/noi-techpark/ohos/fossology-wrapper/-/merge_requests/2

I like how it is written, well done!

@bertolla 
Done, I changed the email for support to help@opendatahub.bz.it... should we merge it to master now?

**Comment by LucaMiotto** [comment]
> > Support transition from reference implementation on NOI infrastructure to Huawei production environment
> > @LucaMiotto Does this mean, that we just have to answer questions, when necessary? Can we close this checkbox?

@Piiit yes I think we can close this checkbox. Now the process is under Huawei responsability. I think we can close the issue too.
